### PR TITLE
JS: Add npm package prerequisites

### PR DESCRIPTION
**Pull request by ghost**
For whenever you get the client working.

### CODE REVIEW

**Comment by bakape** [comment]
Don't think we need this, since the repo is go-gettable without npm. Node is dev-only dependency. Thoughts?

**Comment by ghost** [comment]
So hydron only needs go, and you upload the js to the repo?
You don't have to use the make command, only go get, go build?

**Comment by bakape** [comment]
The js is embedded in the binary. Yes.

**Comment by ghost** [comment]
Okay, no need for this then.

**Pull request closed without merging**
